 
const MENUS = {
    theme : 'dark',
    width : '240px',
    list : [{
        name:' ',
        type:'console',
        icon:'icon_console',
        path:'/console',
        children:[]
    },{
        name:'',
        type:'application',
        icon:'icon_app',
        path:'',
        children:[{
            name:'',
            type:'auditList',
            icon:'',
            path:'/app/audit'
        },{
            name:'',
            type:'repository',
            icon:'',
            path:'/app/list'
        }]
    },{
        name:'',
        type:'developer',
        icon:'icon_developer',
        path:'/developer/list',
        children:[]
    },{
        name:'',
        type:'resource',
        icon:'icon_resource',
        path:'/resource/list',
        children:[]
    },{
        name:'',
        type:'statistics',
        icon:'icon_statistics',
        path:'',
        children:[{
            name:'',
            type:'distribution',
            icon:'',
            path:'/statistics/distribution'
        },{
            name:'',
            type:'deploy',
            icon:'',
            path:'/statistics/deploy'
        },{
            name:'',
            type:'run',
            icon:'',
            path:'/statistics/run'
        }]
    },{
        name:'',
        type:'operate',
        icon:'icon_operate',
        path:'',
        children:[{
            name:'',
            type:'recommend',
            icon:'',
            path:'/operate/recommend'
        },{
            name:'',
            type:'gateway',
            icon:'',
            path:'/operate/gateway'
        },{
            name:'',
            type:'notice',
            icon:'',
            path:'/operate/notice'
        },{
            name:'',
            type:'comments',
            icon:'',
            path:'/operate/comments'
        }]
    },{
        name:'系统设置',
        type:'system',
        icon:'icon_system',
        path:'',
        children:[{
            name:'管理员管理',
            type:'managerList',
            icon:'',
            path:'/system/manager'
        },{
            name:'类别管理',
            type:'managerType',
            icon:'',
            path:'/system/type'
        },{
            name:'系统日志',
            type:'logs',
            icon:'',
            path:'/system/logs'
        }]
    }]
}


export default MENUS
